image: ubuntu:18.04

stages:
  - build
  - test

before_script:
  - wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz
  - tar -zxvf cmake-3.16.5.tar.gz
  - cd cmake-3.16.5
  - ./bootstrap
  - make 
  - sudo make install 
  - apt-get update -yqq
  - apt-get install -yqq qt5-default
  - apt-get install -yqq doxygen

build-program:
  stage: build
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake ..
    - make aWareHouse
  artifacts:
    paths:
      - cmake-build/

doxygen:
  stage: build
  script:
    - doxygen docs/doxygen.conf
    - mv docs/html/ public/
  artifacts:
    paths:
     - public
  only:
    - master

google-test:
  stage: test
  script:
    - cd cmake-build
    - make test
  dependencies:
    - build-program
