image: ubuntu:20.04

stages:
  - build
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -yqq cmake
  - apt-get install -yqq git-all
  - apt-get install -yqq build-essential
  - apt-get install -yqq libgl1-mesa-dev
  - apt-get install -yqq qtdeclarative5-dev
  - apt-get install -yqq qtquickcontrols2-5-dev
  - apt-get install -yqq doxygen

build-program:
  stage: build
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake .. && cmake ../src && cmake ../test/GTest
    - make src
  artifacts:
    paths:
      - cmake-build/

doxygen:
  stage: build
  script:
    - doxygen docs/doxygen.conf
    - mv docs/html/ public/
  artifacts:
    paths:
     - public
  only:
    - master

google-test:
  stage: test
  script:
    - cd cmake-build
    - make test
  dependencies:
    - build-program
