image: ubuntu:18.04

stages:
  - build
  - test

before_script:
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >dev/null
  - apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - apt-get update -yqq
  - apt-get install -yqq cmake --classic
  - apt-get install -yqq qt5-default
  - apt-get install -yqq doxygen

build-program:
  stage: build
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake ..
    - make aWareHouse
  artifacts:
    paths:
      - cmake-build/

doxygen:
  stage: build
  script:
    - doxygen docs/doxygen.conf
    - mv docs/html/ public/
  artifacts:
    paths:
     - public
  only:
    - master

google-test:
  stage: test
  script:
    - cd cmake-build
    - make test
  dependencies:
    - build-program
