image: "archlinux"

stages:
  - build
  - test

before_script:
  - pacman -Syu
  - pacman -S cmake 3.20.1-1
  - pacman -S git 2.31.1-1
  - pacman -S base-devel
  - pacman -S qt6-base 6.0.3-1
  - pacman -S qt6-declarative 6.0.3-1
  - pacman -S qt6-quickcontrols2 6.0.3-1
  - pacman -S doxygen 1.9.1-1

build-program:
  stage: build
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake ..
    - make
  artifacts:
    paths:
      - cmake-build/

doxygen:
  stage: build
  script:
    - doxygen docs/doxygen.conf
    - mv docs/html/ public/
  artifacts:
    paths:
     - public
  only:
    - master

google-test:
  stage: test
  script:
    - cd cmake-build
    - make test
  dependencies:
    - build-program
