image:
  name: "archlinux:20200705"
  entrypoint: ["/bin/sh", "-l", "-c"]

stages:
  - build
  - test

before_script:
  - pacman -Syu git-2.31.1-1
  - pacman -Syu cmake-3.20.1-1
  - pacman -Syu base-devel
  - pacman -Syu qt6-base-6.0.3-1
  - pacman -Syu qt6-declarative-6.0.3-1
  - pacman -Syu qt6-quickcontrols2-6.0.3-1
  - pacman -Syu doxygen-1.9.1-1

build-program:
  stage: build
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake ..
    - make
  artifacts:
    paths:
      - cmake-build/

doxygen:
  stage: build
  script:
    - doxygen docs/doxygen.conf
    - mv docs/html/ public/
  artifacts:
    paths:
     - public
  only:
    - master

google-test:
  stage: test
  script:
    - cd cmake-build
    - make test
  dependencies:
    - build-program
